In [48]:
import pandas as pd
import numpy as np


In [29]:
# Define the column names
mnames = ['movie_id', 'title', 'genres']
rnames = ['user_id', 'movie_id', 'rating', 'timestamp']
unames = ['user_id', 'gender', 'age', 'occupation', 'zip']
# Load the .dat file into a pandas DataFrame
movies = pd.read_csv('.\ml-1m\movies.dat', sep='::', header=None, names=mnames, engine='python', encoding='latin1')
ratings = pd.read_csv(r'.\ml-1m\ratings.dat', sep='::', header=None, names=rnames, engine='python', encoding='latin1')
users = pd.read_csv(r'.\ml-1m\users.dat', sep='::', header=None, names=unames, engine='python', encoding='latin1')

In [33]:
users.dtypes

user_id        int64
gender        object
age            int64
occupation     int64
zip           object
dtype: object

In [35]:
print(ratings.head())

   user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291


In [36]:
print(movies.head())

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy


In [46]:
min_rating = min(ratings["rating"])
max_rating = max(ratings["rating"])
print(f"Max Rating: {max_rating}")
print(f"Min Rating: {min_rating}")

Max Rating: 5
Min Rating 1


In [42]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000209 entries, 0 to 1000208
Data columns (total 4 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   user_id    1000209 non-null  int64
 1   movie_id   1000209 non-null  int64
 2   rating     1000209 non-null  int64
 3   timestamp  1000209 non-null  int64
dtypes: int64(4)
memory usage: 30.5 MB


In [56]:
ratingMatrix = np.ndarray(shape=(np.max(ratings.user_id.values), np.max(ratings.movie_id.values)),
                        dtype=np.uint8)
ratingMatrix [ratings.user_id.values-1, ratings.movie_id.values-1] = ratings.rating.values
print(ratingMatrix)


[[5 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [3 0 0 ... 0 0 0]]
